### ISSUE TITLE
go-firestorm User Group

### ISSUE THREAD

**Issue by simenandre** [jschoedt/go-firestorm#3]
The link for [go-firestorm User Group](https://groups.google.com/forum/?fromgroups#!forum/go-firestorm) does not work, or rather I do not have access to it. Is it meant to be non-public or is something wrong?

Thanks again for an awesome project, @jschoedt!

**Comment by jschoedt** [comment]
Thanks for pointing this out. 
I have changed some group settings and you should be able to join now.
