### ISSUE TITLE
How to use cache?

### ISSUE THREAD

**Issue by jacksgt** [jschoedt/go-firestorm#4]
Hello,

thanks you for this simple and straightforward package!

I'm successfully using in one of my current projects. The DB interface works perfectly fine, however I have difficulties getting the caching layer to work.

I have written a little middleware that injects the `CacheHandler`.
```go
func CacheMiddleware(next http.Handler) http.Handler {
	return firestorm.CacheHandler(next.ServeHTTP)
}
```
and adding it to my router (go-chi):
```go
r.Use(db.CacheMiddleware)
r.Get("/", indexHandler)
```
From each of my HTTP handlers, I'm then passing the context onto the db functions:
```go
func countryHandler(w http.ResponseWriter, r *http.Request) {
    ...
	countryData, err := LoadCountryData(r.Context())
	if err != nil {
		log.Printf("Failed to load  data: %s", err)
		http.Error(w, "Internal Server Error", 500)
		return
	}
    ...
}

// var Client *firestorm.FSClient was initialized somewhere else
func LoadCountryData(ctx context.Context) (*types.Country, error) {
	var c = &types.Country{ID: slug}
	_, err := Client.NewRequest().SetLoadPaths(firestorm.AllEntities).GetEntities(ctx, c)()
	if IsNotFoundError(err) {
		return nil, nil
	} else if err != nil {
		return nil, err
	}

	return c, nil
}
```

Nevertheless, I still get the message "Warning. Consider adding the CacheHandler middleware for the session cache to work" and subsequent database calls don't seem to be faster.

Am I using the cache (in)correctly? Is there a way I can verify its behavior?

**Comment by jschoedt** [comment]
Hi thanks for the feedback,

Im not sure about _go-chi_ but what you are doing looks correct. It should not give you that warning. Have you tried:
`r.With(db.CacheMiddleware).Get("/", indexHandler)`
Does that work bettet?

Also the cache is a session (request) cache so it will only cache entities that are loaded in the same session. It will not cache entities between different requests unfortunately. I am working on a branch (https://github.com/jschoedt/go-firestorm/tree/cache) that does that using eg. Redis, but it is still work in progress. I do plan to continue working on it soon as I need that feature myself :-)

What you could do is add your own map with the _ContextKeySCache_, but instead use a global map that you control and not create a new one for each request like it is done here by the default CacheHandler:

```
func CacheHandler(next http.HandlerFunc) http.HandlerFunc {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := context.WithValue(r.Context(), ContextKeySCache, make(map[string]interface{}))
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```
You would need to manually invalidate the global map which is not straight forward.

**Comment by jacksgt** [comment]
Thanks for getting back to me!

After a bit more playing around with my code, I am no longer getting the cache warning. I think I will submit a PR with the CacheMiddleware shown above and a bit more documentation for the README - let me know if this is fine for you.

Anyway, since the session cache does not work between requests, it does not suit my usecase.
I had a quick look at the `cache` branch. Is that currently usable? Any gotchas I should look out for?
(I currently don't need strong consistency or anything like that).

**Comment by jschoedt** [comment]
Nice, how did you get it to work? Maybe I can add it to the documentation.

I do plan to change the CacheHandler to:
```
func CacheHandler(next http.Handler) http.Handler {
...
}
```

So it can be used directly as:
`r.Use(firestorm.CacheHandler)`

The cache branch can be used but there are still some bugs that needs attention. Also the documentation is not in place. You are welcome to try it out.
You need to implement the _firestorm.Cache_ interface yourself, but I would like to provide implementations for local Map, Redis and Memcache eg. on App Engine when "releasing" it. What are you planning to use as cache?

Yes of-cause pull requests are welcome :+1:

**Comment by jacksgt** [comment]
> Nice, how did you get it to work? Maybe I can add it to the documentation.

I cannot really recommend this to anyone, but it works for me :-)
(Mainly because I'm running a serverless function so after a few minutes the entire function state is cleaned up anyway).
```go
var cacheMap map[string]interface{} = make(map[string]interface{})

func CacheHandler(next http.HandlerFunc) http.HandlerFunc {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := context.WithValue(r.Context(), firestorm.ContextKeySCache, cacheMap)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// this is not safe, don't do this at home
func InvalidateCache() {
	cacheMap = make(map[string]interface{})
}

```

> 
> I do plan to change the CacheHandler to:
> ...
> So it can be used directly as:
> `r.Use(firestorm.CacheHandler)`

I think you should leave the "primitive" version (i.e. the raw handler) available for people who are just using plain net/http (without routing frameworks).
But I added a CacheMiddleware helper function (which wraps around CacheHandler) to the PR.

> The cache branch can be used but there are still some bugs that needs attention. Also the documentation is not in place. You are welcome to try it out.
> You need to implement the _firestorm.Cache_ interface yourself, but I would like to provide implementations for local Map, Redis and Memcache eg. on App Engine when "releasing" it. What are you planning to use as cache?

For my use-case, just the local map is sufficient. In general, I like the idea of having multiple backends for the cache.

> Yes of-cause pull requests are welcome +1

Excellent. PR is open :-)

**Comment by jschoedt** [comment]
Thank you for the PR. You are right. Better keep the primitive version :+1: 

I'm thinking a local map is not well suited for cloud based applications as it will only live in a single process. Out of curiosity, can the cacheMap live between function calls?

**Comment by jacksgt** [comment]
> Thank you for the PR. You are right. Better keep the primitive version +1
> 
> I'm thinking a local map is not well suited for cloud based applications as it will only live in a single process. Out of curiosity, can the cacheMap live between function calls?

I agree that the use case can be somewhat limited.
Most Serverless / Functions-as-a-Service platform will timeout the function after ~10 minutes (+/- 5 minutes) without any invocation. This means when the function is not triggered within that amount of time, the global state of the function will be cleared and next time it will be initialized from scratch (in this specific case, it would also clear the global map).

The good thing about a global map is that the overhead (compared to redis etc.) is practically zero and it's also very easy to get started (no external dependencies required).
